
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.*;
import com.sun.speech.freetts.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Xbenx
 */
public class TicTok extends javax.swing.JFrame {

    /**
     * Creates new form TicTok
     */
    public TicTok() {
        initComponents();
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
             jButton4.setEnabled(false);
                  jButton5.setEnabled(false);
                       jButton6.setEnabled(false);
                            jButton7.setEnabled(false);
                                 jButton8.setEnabled(false);
                                      jButton9.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("START");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    boolean round=false;
    int clicked=1;
    private static final String VOC="kevin16";
      public void winEffect(JButton b1,JButton b2,JButton b3,Voice voice)
    {
        if(!round)
        {
               voice.speak("X is the winner");

        }
        else
        {
             voice.speak("O is the winner");

        }
        //jLabel1.setText(msg);        
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                jButton3.setEnabled(false);
                clicked++;
                
        if(round)
        {
            jButton3.setText("X");
        }else
        {
        jButton3.setText("O");
        }
        round=!round;getTheWinner();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(false);    clicked++;
        if(round)
        {
            jButton1.setText("X");
        }else
        {
        jButton1.setText("O");
        }
        round=!round;getTheWinner();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                jButton2.setEnabled(false);    clicked++;
        if(round)
        {
            jButton2.setText("X");
        }else
        {
        jButton2.setText("O");
        }    round=!round; getTheWinner();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                jButton4.setEnabled(false);    clicked++;
        if(round)
        {
            jButton4.setText("X");
        }else
        {
        jButton4.setText("O");
        }   round=!round;getTheWinner();     // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                jButton5.setEnabled(false);    clicked++;
        if(round)
        {
            jButton5.setText("X");
        }else
        {
        jButton5.setText("O");
        }    round=!round;getTheWinner();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                jButton6.setEnabled(false);    clicked++;
        if(round)
        {
            jButton6.setText("X");
        }else
        {
        jButton6.setText("O");
        }       round=!round;getTheWinner(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                jButton7.setEnabled(false);    clicked++;
        if(round)
        {
            jButton7.setText("X");
        }else
        {
        jButton7.setText("O");
        }       round=!round;getTheWinner(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
                jButton8.setEnabled(false);    clicked++;
        if(round)
        {
            jButton8.setText("X");
        }else
        {
        jButton8.setText("O");
        }      round=!round;getTheWinner();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
                jButton9.setEnabled(false);    clicked++;
        if(round)
        {
            jButton9.setText("X");
        }else
        {
        jButton9.setText("O");
        }       round=!round; getTheWinner();// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
             jButton4.setEnabled(true);
                  jButton5.setEnabled(true);
                       jButton6.setEnabled(true);
                            jButton7.setEnabled(true);
                                 jButton8.setEnabled(true);
                                      jButton9.setEnabled(true);
                                      jButton1.setText("");
                                      jButton2.setText("");
                                       jButton3.setText("");
                                        jButton4.setText("");
                                       jButton5.setText("");
                                          jButton6.setText("");
                                             jButton7.setText("");
                                                jButton8.setText("");
                                                   jButton9.setText("");
                                                   clicked=1;
    }//GEN-LAST:event_jButton10ActionPerformed
 
    boolean win=false;
    
    public void getTheWinner()
    { 
         Voice voice;
        VoiceManager vm = VoiceManager.getInstance();
        voice=vm.getVoice(VOC);
        voice.allocate();
        if (!jButton1.getText().equals("")&&jButton1.getText().equals(jButton2.getText())&&jButton1.getText().equals(jButton3.getText()) )
        {   jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
             jButton4.setEnabled(false);
                  jButton5.setEnabled(false);
                       jButton6.setEnabled(false);
                            jButton7.setEnabled(false);
                                 jButton8.setEnabled(false);
                                      jButton9.setEnabled(false);
           winEffect(jButton1,jButton2,jButton3,voice);
           win =true;
        }
        if (!jButton4.getText().equals("")&&jButton4.getText().equals(jButton5.getText())&&jButton4.getText().equals(jButton6.getText()) )
        {jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
             jButton4.setEnabled(false);
                  jButton5.setEnabled(false);
                       jButton6.setEnabled(false);
                            jButton7.setEnabled(false);
                                 jButton8.setEnabled(false);
                                      jButton9.setEnabled(false);
           winEffect(jButton4,jButton5,jButton6,voice);
           win =true;
        }
        if (!jButton7.getText().equals("")&&jButton7.getText().equals(jButton8.getText())&&jButton7.getText().equals(jButton9.getText()) )
        {jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
             jButton4.setEnabled(false);
                  jButton5.setEnabled(false);
                       jButton6.setEnabled(false);
                            jButton7.setEnabled(false);
                                 jButton8.setEnabled(false);
                                      jButton9.setEnabled(false);
            winEffect(jButton7,jButton8,jButton9,voice);
            win =true;
        }
        if (!jButton1.getText().equals("")&&jButton1.getText().equals(jButton4.getText())&&jButton1.getText().equals(jButton7.getText()) )
        {jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
             jButton4.setEnabled(false);
                  jButton5.setEnabled(false);
                       jButton6.setEnabled(false);
                            jButton7.setEnabled(false);
                                 jButton8.setEnabled(false);
                                      jButton9.setEnabled(false);
            winEffect(jButton1,jButton4,jButton7,voice);
            win =true;
        }
        if (!jButton2.getText().equals("")&&jButton2.getText().equals(jButton5.getText())&&jButton2.getText().equals(jButton8.getText()) )
        {jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
             jButton4.setEnabled(false);
                  jButton5.setEnabled(false);
                       jButton6.setEnabled(false);
                            jButton7.setEnabled(false);
                                 jButton8.setEnabled(false);
                                      jButton9.setEnabled(false);
           winEffect(jButton2,jButton5,jButton8,voice);
           win =true;
        }
        if (!jButton3.getText().equals("")&&jButton3.getText().equals(jButton6.getText())&&jButton3.getText().equals(jButton9.getText()) )
        {jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
             jButton4.setEnabled(false);
                  jButton5.setEnabled(false);
                       jButton6.setEnabled(false);
                            jButton7.setEnabled(false);
                                 jButton8.setEnabled(false);
                                      jButton9.setEnabled(false);
            winEffect(jButton3,jButton6,jButton9,voice);
            win =true;
        }
        if (!jButton1.getText().equals("")&&jButton1.getText().equals(jButton5.getText())&&jButton1.getText().equals(jButton9.getText()) )
        {jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
             jButton4.setEnabled(false);
                  jButton5.setEnabled(false);
                       jButton6.setEnabled(false);
                            jButton7.setEnabled(false);
                                 jButton8.setEnabled(false);
                                      jButton9.setEnabled(false);
           winEffect(jButton1,jButton5,jButton9,voice);
           win =true;
        }
        if (!jButton3.getText().equals("")&&jButton3.getText().equals(jButton5.getText())&&jButton3.getText().equals(jButton7.getText()) )
        {jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
             jButton4.setEnabled(false);
                  jButton5.setEnabled(false);
                       jButton6.setEnabled(false);
                            jButton7.setEnabled(false);
                                 jButton8.setEnabled(false);
                                      jButton9.setEnabled(false);
            winEffect(jButton3,jButton5,jButton7,voice);
            win =true;
        }
        else if (clicked==10 && win==false)
        {
                voice.speak("None win");
        }        
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
